Added the required VIMDB_ROOT env var support

diff --git a/internal/gvimdb b/internal/gvimdb
--- a/internal/gvimdb
+++ b/internal/gvimdb
@@ -1,2 +1,6 @@
-gvim -R --servername VIMDB -c "ConqueTermSplit gdb -ex \"source /home/kris/ProgrammingHome/VimDb/internal/gdb.py\" $*"
+if [ -z "$VIMDB_ROOT" ]; then
+    echo "Error: Need to set VIMDB_ROOT"
+    exit 1
+fi  
+gvim -R --servername VIMDB -c "ConqueTermSplit gdb -ex \"source $VIMDB_ROOT/gdb.py\" $*"
 
diff --git a/internal/vimdb b/internal/vimdb
--- a/internal/vimdb
+++ b/internal/vimdb
@@ -1,2 +1,5 @@
-vim -R --servername VIMDB -c "ConqueTermSplit gdb -ex \"source /home/kris/ProgrammingHome/VimDb/internal/gdb.py\" $*"
-
+if [ -z "$VIMDB_ROOT" ]; then
+    echo "Error: Need to set VIMDB_ROOT"
+    exit 1
+fi  
+vim -R --servername VIMDB -c "ConqueTermSplit gdb -ex \"source $VIMDB_ROOT/gdb.py\" $*"
